### ISSUE TITLE
Overwrite/custom build.rs for final binaries

### ISSUE THREAD

**Issue by xangelix** [ronnychevalier/cargo-multivers#10]
See discussion: https://github.com/ronnychevalier/cargo-multivers/discussions/9

**Comment by ronnychevalier** [comment]
FYI I pushed a feature on `main` where you can specify your on runner instead of the one automatically generated:

```
cargo multivers --runner-manifest-path path/to/runner/Cargo.toml
```

where `path/to/runner/Cargo.toml` contains something like:

```toml
[package]
name = "custom-runner"
publish = false
edition = "2024"

[dependencies]
multivers-runner = "0.3"

[profile.release]
lto = true
strip = "symbols"
opt-level = "z"
codegen-units = 1
panic = "abort"
```

and `path/to/runner/src/main.rs` contains something like:

```rust
#![no_main]
pub use multivers_runner::main;
```

This way you can add your own `build.rs` (or any other file) as long as the dependency `multivers-runner` is added and `multivers_runner::main` is used as the entrypoint.

Let me know if this works, and I will close this issue when this feature is released.
